ALTER TABLE build_steps
    ADD COLUMN IF NOT EXISTS command TEXT NOT NULL DEFAULT 'sh',
    ADD COLUMN IF NOT EXISTS args JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS env JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS working_dir TEXT NOT NULL DEFAULT '.',
    ADD COLUMN IF NOT EXISTS timeout_seconds INTEGER NOT NULL DEFAULT 0;
