version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "uv"
    directory: "/mcp"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

    groups:
      python-runtime:
        dependency-type: "production"
        patterns:
          - "*"
      python-dev:
        dependency-type: "development"
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
