root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/server"
bin = "./tmp/server"
include_ext = ["go", "mod", "sum", "yaml", "yml"]
exclude_dir = ["tmp", "docs"]
delay = 500
stop_on_error = true

[log]
time = false

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
