version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck

  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable:
        - shadow
