package service

import (
	buildsvc "github.com/radiation/coyote-ci/backend/internal/service/build"
	webhooksvc "github.com/radiation/coyote-ci/backend/internal/service/webhook"
	workersvc "github.com/radiation/coyote-ci/backend/internal/service/worker"
)

type BuildService = buildsvc.BuildService
type BuildServiceConfig = buildsvc.BuildServiceConfig
type CreateBuildInput = buildsvc.CreateBuildInput
type CreateBuildSourceInput = buildsvc.CreateBuildSourceInput
type CreateBuildStepInput = buildsvc.CreateBuildStepInput
type QueueBuildCustomStepInput = buildsvc.QueueBuildCustomStepInput
type CreateBuildTriggerInput = buildsvc.CreateBuildTriggerInput
type CreatePipelineBuildInput = buildsvc.CreatePipelineBuildInput
type CreateRepoBuildInput = buildsvc.CreateRepoBuildInput
type StepCompletionReport = buildsvc.StepCompletionReport

var NewBuildService = buildsvc.NewBuildService
var NewBuildServiceFromConfig = buildsvc.NewBuildServiceFromConfig

var ErrBuildNotFound = buildsvc.ErrBuildNotFound
var ErrBuildStepNotFound = buildsvc.ErrBuildStepNotFound
var ErrProjectIDRequired = buildsvc.ErrProjectIDRequired
var ErrInvalidBuildStatusTransition = buildsvc.ErrInvalidBuildStatusTransition
var ErrInvalidBuildStepTransition = buildsvc.ErrInvalidBuildStepTransition
var ErrStaleStepClaim = buildsvc.ErrStaleStepClaim
var ErrRunnerNotConfigured = buildsvc.ErrRunnerNotConfigured
var ErrRunnerWorkspaceNotSupported = buildsvc.ErrRunnerWorkspaceNotSupported
var ErrCustomTemplateStepsRequired = buildsvc.ErrCustomTemplateStepsRequired
var ErrCustomTemplateStepCommandRequired = buildsvc.ErrCustomTemplateStepCommandRequired
var ErrPipelineYAMLRequired = buildsvc.ErrPipelineYAMLRequired
var ErrRepoURLRequired = buildsvc.ErrRepoURLRequired
var ErrSourceTargetRequired = buildsvc.ErrSourceTargetRequired
var ErrRepoFetcherNotConfigured = buildsvc.ErrRepoFetcherNotConfigured
var ErrPipelineFileNotFound = buildsvc.ErrPipelineFileNotFound
var ErrInvalidPipelinePath = buildsvc.ErrInvalidPipelinePath
var ErrArtifactNotFound = buildsvc.ErrArtifactNotFound
var ErrArtifactStorageProviderNotConfigured = buildsvc.ErrArtifactStorageProviderNotConfigured
var ErrSourceResolverNotConfigured = buildsvc.ErrSourceResolverNotConfigured
var ErrExecutionWorkspaceRootNotConfigured = buildsvc.ErrExecutionWorkspaceRootNotConfigured
var ErrExecutionJobRepoNotConfigured = buildsvc.ErrExecutionJobRepoNotConfigured
var ErrExecutionJobNotFound = buildsvc.ErrExecutionJobNotFound
var ErrExecutionJobNotRetryable = buildsvc.ErrExecutionJobNotRetryable
var ErrInvalidRerunStepIndex = buildsvc.ErrInvalidRerunStepIndex

var BuildTemplateDefault = buildsvc.BuildTemplateDefault
var BuildTemplateTest = buildsvc.BuildTemplateTest
var BuildTemplateBuild = buildsvc.BuildTemplateBuild
var BuildTemplateCustom = buildsvc.BuildTemplateCustom
var BuildTemplateFail = buildsvc.BuildTemplateFail

type ExecutionWorkerService = workersvc.ExecutionWorkerService
type WorkerService = workersvc.ExecutionWorkerService
type WorkerRunnableStep = workersvc.WorkerRunnableStep
type RunnableStep = workersvc.WorkerRunnableStep
type WorkerStepExecutionReport = workersvc.WorkerStepExecutionReport
type StepExecutionReport = workersvc.WorkerStepExecutionReport
type WorkerLeaseRecoveryStats = workersvc.WorkerLeaseRecoveryStats
type WorkerRecoveryStats = workersvc.WorkerLeaseRecoveryStats

var NewExecutionWorkerService = workersvc.NewExecutionWorkerService
var NewWorkerService = workersvc.NewExecutionWorkerService
var NewExecutionWorkerServiceWithLease = workersvc.NewExecutionWorkerServiceWithLease
var NewWorkerServiceWithLease = workersvc.NewExecutionWorkerServiceWithLease

type DeliveryIngressService = webhooksvc.DeliveryIngressService
type DeliveryIngressResult = webhooksvc.DeliveryIngressResult
type WebhookLogContext = webhooksvc.WebhookLogContext

// Backward-compatible aliases retained for existing callers.
type WebhookIngressService = webhooksvc.DeliveryIngressService
type WebhookIngressResult = webhooksvc.DeliveryIngressResult

type WebhookMatchedBuild = webhooksvc.WebhookMatchedBuild
type WebhookTriggerInput = webhooksvc.WebhookTriggerInput
type WebhookTriggerResult = webhooksvc.WebhookTriggerResult
type WebhookFilterDecision = webhooksvc.WebhookFilterDecision
type WebhookFilterDecisionReason = webhooksvc.WebhookFilterDecisionReason
type WebhookFilterConfig = webhooksvc.WebhookFilterConfig

// Backward-compatible trigger-filter aliases.
type WebhookTriggerDecision = webhooksvc.WebhookFilterDecision
type WebhookTriggerDecisionReason = webhooksvc.WebhookFilterDecisionReason
type WebhookJobTriggerConfig = webhooksvc.WebhookFilterConfig

var NewDeliveryIngressService = webhooksvc.NewDeliveryIngressService
var NewWebhookIngressService = webhooksvc.NewDeliveryIngressService
var NewWebhookLogContext = webhooksvc.NewWebhookLogContext
var WithWebhookLogContext = webhooksvc.WithWebhookLogContext
var WebhookLogContextFromContext = webhooksvc.WebhookLogContextFromContext
var WebhookLogFields = webhooksvc.WebhookLogFields
var ShouldTriggerBuild = webhooksvc.WebhookFilterShouldTriggerBuild
var NormalizeJobTriggerMode = webhooksvc.NormalizeWebhookFilterMode

var ErrDeliveryRepoNotConfigured = webhooksvc.ErrDeliveryRepoNotConfigured
var ErrDeliveryIDRequired = webhooksvc.ErrDeliveryIDRequired
var ErrDeliveryProviderRequired = webhooksvc.ErrDeliveryProviderRequired
var ErrInvalidDeliveryTransition = webhooksvc.ErrInvalidDeliveryTransition

var ErrWebhookDeliveryRepoNotConfigured = webhooksvc.ErrDeliveryRepoNotConfigured
var ErrWebhookDeliveryIDRequired = webhooksvc.ErrDeliveryIDRequired
var ErrWebhookProviderRequired = webhooksvc.ErrDeliveryProviderRequired
var ErrWebhookInvalidDeliveryTransition = webhooksvc.ErrInvalidDeliveryTransition

const WebhookFilterDecisionMatched = webhooksvc.WebhookFilterDecisionMatched
const WebhookFilterDecisionDeletedRef = webhooksvc.WebhookFilterDecisionDeletedRef
const WebhookFilterDecisionUnsupportedRefType = webhooksvc.WebhookFilterDecisionUnsupportedRefType
const WebhookFilterDecisionFilteredBranch = webhooksvc.WebhookFilterDecisionFilteredBranch
const WebhookFilterDecisionFilteredTag = webhooksvc.WebhookFilterDecisionFilteredTag
const WebhookFilterDecisionFilteredByMode = webhooksvc.WebhookFilterDecisionFilteredByMode

const WebhookTriggerDecisionMatched = webhooksvc.WebhookFilterDecisionMatched
const WebhookTriggerDecisionDeletedRef = webhooksvc.WebhookFilterDecisionDeletedRef
const WebhookTriggerDecisionUnsupportedRefType = webhooksvc.WebhookFilterDecisionUnsupportedRefType
const WebhookTriggerDecisionFilteredBranch = webhooksvc.WebhookFilterDecisionFilteredBranch
const WebhookTriggerDecisionFilteredTag = webhooksvc.WebhookFilterDecisionFilteredTag
const WebhookTriggerDecisionFilteredByMode = webhooksvc.WebhookFilterDecisionFilteredByMode
