apiVersion: v1
kind: ServiceAccount
metadata:
  name: coyote-workspace-verifier
  namespace: coyote-ci
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: coyote-workspace-verifier-token
  namespace: coyote-ci
  annotations:
    kubernetes.io/service-account.name: coyote-workspace-verifier
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coyote-workspace-verifier
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coyote-workspace-verifier
subjects:
  - kind: ServiceAccount
    name: coyote-workspace-verifier
    namespace: coyote-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coyote-workspace-verifier
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coyote-workspace-verifier
  namespace: coyote-ci
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coyote-workspace-verifier
  namespace: coyote-ci
subjects:
  - kind: ServiceAccount
    name: coyote-workspace-verifier
    namespace: coyote-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coyote-workspace-verifier