// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/webhooks/github": {
            "post": {
                "description": "Verifies a GitHub webhook signature and triggers builds for matching jobs on push events.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhooks"
                ],
                "summary": "Ingest GitHub webhook",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PushEventEnvelope"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/api.PushEventEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds": {
            "get": {
                "description": "Lists all builds sorted by newest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "List builds",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BuildListEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new build in pending status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Create build",
                "parameters": [
                    {
                        "description": "Build create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateBuildRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.BuildEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/jobs/{jobID}/retry": {
            "post": {
                "description": "Creates a new build attempt containing a retry of the failed execution job.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Retry failed execution job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Execution Job ID",
                        "name": "jobID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.RetryJobEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/pipeline": {
            "post": {
                "description": "Parses and validates pipeline YAML, then creates a queued build with resolved steps.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Create build from pipeline YAML",
                "parameters": [
                    {
                        "description": "Pipeline build create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreatePipelineBuildRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.BuildEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/repo": {
            "post": {
                "description": "Clones a repository, loads .coyote/pipeline.yml, then creates a queued build.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Create build from repository",
                "parameters": [
                    {
                        "description": "Repo build create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateRepoBuildRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.BuildEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/{buildID}": {
            "get": {
                "description": "Returns build details by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Get build",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "buildID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BuildEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/{buildID}/artifacts": {
            "get": {
                "description": "Returns persisted artifact metadata for a build.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "List build artifacts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "buildID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BuildArtifactsEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/{buildID}/artifacts/{artifactID}/download": {
            "get": {
                "description": "Streams stored artifact content for a build artifact.",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Download build artifact",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "buildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Artifact ID",
                        "name": "artifactID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "binary payload",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/{buildID}/complete": {
            "post": {
                "description": "Transitions build status from running to success.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Complete build",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "buildID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BuildEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/{buildID}/fail": {
            "post": {
                "description": "Transitions build status from running to failed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Fail build",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "buildID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BuildEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/{buildID}/logs": {
            "get": {
                "description": "Returns log lines for a build.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Get build logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "buildID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BuildLogsEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/{buildID}/queue": {
            "post": {
                "description": "Transitions build status from pending to queued.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Queue build",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "buildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Queue build request",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.QueueBuildRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BuildEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/{buildID}/rerun": {
            "post": {
                "description": "Creates a new build attempt rerunning from a selected step index.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Rerun build from step",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "buildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rerun request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RerunBuildFromStepRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BuildEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/{buildID}/start": {
            "post": {
                "description": "Transitions build status from queued to running.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Start build",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "buildID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BuildEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/{buildID}/steps": {
            "get": {
                "description": "Returns steps for a build.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Get build steps",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "buildID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BuildStepsEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/{buildID}/steps/{stepIndex}/logs": {
            "get": {
                "description": "Returns persisted log chunks for a build step.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Get build step logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "buildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Step index",
                        "name": "stepIndex",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Replay cursor (exclusive sequence number)",
                        "name": "after",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum chunks to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.StepLogsEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/builds/{buildID}/steps/{stepIndex}/logs/stream": {
            "get": {
                "description": "Streams build step log chunks over SSE with cursor resume support.",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "builds"
                ],
                "summary": "Stream build step logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "buildID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Step index",
                        "name": "stepIndex",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Replay cursor (exclusive sequence number)",
                        "name": "after",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/events/push": {
            "post": {
                "description": "Triggers builds for matching enabled jobs configured for push events.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Ingest push event",
                "parameters": [
                    {
                        "description": "Push event payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.PushEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PushEventEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns a simple liveness response.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/jobs": {
            "get": {
                "description": "Lists all jobs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "List jobs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.JobListEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new job.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Create job",
                "parameters": [
                    {
                        "description": "Job create request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateJobRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.JobEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/jobs/{jobID}": {
            "get": {
                "description": "Returns job details by id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Get job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.JobEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing job.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Update job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Job update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UpdateJobRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.JobEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/jobs/{jobID}/builds": {
            "get": {
                "description": "Returns builds triggered by a specific job, sorted newest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "List builds for a job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.BuildListEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/jobs/{jobID}/run": {
            "post": {
                "description": "Triggers an immediate build for a job.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Run job now",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "jobID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.BuildEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.BuildArtifactResponse": {
            "type": "object",
            "properties": {
                "build_id": {
                    "type": "string"
                },
                "checksum_sha256": {
                    "type": "string"
                },
                "content_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "download_url_path": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                }
            }
        },
        "api.BuildArtifactsEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.BuildArtifactsResponse"
                }
            }
        },
        "api.BuildArtifactsResponse": {
            "type": "object",
            "properties": {
                "artifacts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.BuildArtifactResponse"
                    }
                },
                "build_id": {
                    "type": "string"
                }
            }
        },
        "api.BuildEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.BuildResponse"
                }
            }
        },
        "api.BuildListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.BuildListResponse"
                }
            }
        },
        "api.BuildListResponse": {
            "type": "object",
            "properties": {
                "builds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.BuildResponse"
                    }
                }
            }
        },
        "api.BuildLogResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "step_name": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "api.BuildLogsEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.BuildLogsResponse"
                }
            }
        },
        "api.BuildLogsResponse": {
            "type": "object",
            "properties": {
                "build_id": {
                    "type": "string"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.BuildLogResponse"
                    }
                }
            }
        },
        "api.BuildResponse": {
            "type": "object",
            "properties": {
                "actor": {
                    "type": "string"
                },
                "attempt_number": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "current_step_index": {
                    "type": "integer"
                },
                "delivery_id": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "finished_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "pipeline_config_yaml": {
                    "type": "string"
                },
                "pipeline_name": {
                    "type": "string"
                },
                "pipeline_path": {
                    "type": "string"
                },
                "pipeline_source": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "queued_at": {
                    "type": "string"
                },
                "ref_type": {
                    "type": "string"
                },
                "repository_name": {
                    "type": "string"
                },
                "repository_owner": {
                    "type": "string"
                },
                "repository_url": {
                    "type": "string"
                },
                "rerun_from_step_index": {
                    "type": "integer"
                },
                "rerun_of_build_id": {
                    "type": "string"
                },
                "scm_provider": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/api.BuildSourceResponse"
                },
                "source_commit_sha": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "trigger_commit_sha": {
                    "type": "string"
                },
                "trigger_kind": {
                    "type": "string"
                },
                "trigger_ref": {
                    "type": "string"
                }
            }
        },
        "api.BuildSourceInput": {
            "type": "object",
            "properties": {
                "commit_sha": {
                    "type": "string"
                },
                "ref": {
                    "type": "string"
                },
                "repository_url": {
                    "type": "string"
                }
            }
        },
        "api.BuildSourceResponse": {
            "type": "object",
            "properties": {
                "ref": {
                    "type": "string"
                },
                "repository_url": {
                    "type": "string"
                },
                "source_commit_sha": {
                    "type": "string"
                }
            }
        },
        "api.BuildStepResponse": {
            "type": "object",
            "properties": {
                "build_id": {
                    "type": "string"
                },
                "command": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "exit_code": {
                    "type": "integer"
                },
                "finished_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "job": {
                    "$ref": "#/definitions/api.ExecutionJobResponse"
                },
                "name": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "stderr": {
                    "type": "string"
                },
                "stdout": {
                    "type": "string"
                },
                "step_index": {
                    "type": "integer"
                },
                "worker_id": {
                    "type": "string"
                }
            }
        },
        "api.BuildStepsEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.BuildStepsResponse"
                }
            }
        },
        "api.BuildStepsResponse": {
            "type": "object",
            "properties": {
                "build_id": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.BuildStepResponse"
                    }
                }
            }
        },
        "api.CreateBuildRequest": {
            "type": "object",
            "properties": {
                "project_id": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/api.BuildSourceInput"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.CreateBuildStepInput"
                    }
                },
                "template": {
                    "type": "string"
                }
            }
        },
        "api.CreateBuildStepInput": {
            "type": "object",
            "properties": {
                "args": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "command": {
                    "type": "string"
                },
                "env": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "timeout_seconds": {
                    "type": "integer"
                },
                "working_dir": {
                    "type": "string"
                }
            }
        },
        "api.CreateJobRequest": {
            "type": "object",
            "properties": {
                "branch_allowlist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "default_commit_sha": {
                    "type": "string"
                },
                "default_ref": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "pipeline_path": {
                    "type": "string"
                },
                "pipeline_yaml": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "push_branch": {
                    "type": "string"
                },
                "push_enabled": {
                    "type": "boolean"
                },
                "repository_url": {
                    "type": "string"
                },
                "tag_allowlist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "trigger_mode": {
                    "type": "string"
                }
            }
        },
        "api.CreatePipelineBuildRequest": {
            "type": "object",
            "properties": {
                "pipeline_yaml": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "source": {
                    "$ref": "#/definitions/api.BuildSourceInput"
                }
            }
        },
        "api.CreateRepoBuildRequest": {
            "type": "object",
            "properties": {
                "commit_sha": {
                    "type": "string"
                },
                "pipeline_path": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "ref": {
                    "type": "string"
                },
                "repo_url": {
                    "type": "string"
                }
            }
        },
        "api.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/api.ErrorBody"
                }
            }
        },
        "api.ExecutionJobOutputResponse": {
            "type": "object",
            "properties": {
                "build_id": {
                    "type": "string"
                },
                "content_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "declared_path": {
                    "type": "string"
                },
                "destination_uri": {
                    "type": "string"
                },
                "digest": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "kind": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.ExecutionJobResponse": {
            "type": "object",
            "properties": {
                "attempt_number": {
                    "type": "integer"
                },
                "build_id": {
                    "type": "string"
                },
                "command": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "command_preview": {
                    "type": "string"
                },
                "context_dir": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "environment": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "error_message": {
                    "type": "string"
                },
                "finished_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "lineage_root_job_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "outputs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ExecutionJobOutputResponse"
                    }
                },
                "pipeline_file_path": {
                    "type": "string"
                },
                "retry_of_job_id": {
                    "type": "string"
                },
                "source_commit_sha": {
                    "type": "string"
                },
                "source_ref_name": {
                    "type": "string"
                },
                "source_repo_url": {
                    "type": "string"
                },
                "spec_digest": {
                    "type": "string"
                },
                "spec_version": {
                    "type": "integer"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "step_id": {
                    "type": "string"
                },
                "step_index": {
                    "type": "integer"
                },
                "timeout_seconds": {
                    "type": "integer"
                },
                "working_dir": {
                    "type": "string"
                }
            }
        },
        "api.JobEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.JobResponse"
                }
            }
        },
        "api.JobListEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.JobListResponse"
                }
            }
        },
        "api.JobListResponse": {
            "type": "object",
            "properties": {
                "jobs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.JobResponse"
                    }
                }
            }
        },
        "api.JobResponse": {
            "type": "object",
            "properties": {
                "branch_allowlist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "default_commit_sha": {
                    "type": "string"
                },
                "default_ref": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pipeline_path": {
                    "type": "string"
                },
                "pipeline_yaml": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "push_branch": {
                    "type": "string"
                },
                "push_enabled": {
                    "type": "boolean"
                },
                "repository_url": {
                    "type": "string"
                },
                "tag_allowlist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "trigger_mode": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "api.PushEventEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.PushEventResponse"
                }
            }
        },
        "api.PushEventMatchedJob": {
            "type": "object",
            "properties": {
                "build_id": {
                    "type": "string"
                },
                "build_status": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "job_name": {
                    "type": "string"
                }
            }
        },
        "api.PushEventRequest": {
            "type": "object",
            "properties": {
                "commit_sha": {
                    "type": "string"
                },
                "ref": {
                    "type": "string"
                },
                "repository_url": {
                    "type": "string"
                }
            }
        },
        "api.PushEventResponse": {
            "type": "object",
            "properties": {
                "builds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.PushEventMatchedJob"
                    }
                },
                "commit_sha": {
                    "type": "string"
                },
                "created_builds": {
                    "type": "integer"
                },
                "duplicate": {
                    "type": "boolean"
                },
                "matched_jobs": {
                    "type": "integer"
                },
                "ref": {
                    "type": "string"
                },
                "repository_url": {
                    "type": "string"
                }
            }
        },
        "api.QueueBuildRequest": {
            "type": "object",
            "properties": {
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.QueueBuildStepInput"
                    }
                },
                "template": {
                    "type": "string"
                }
            }
        },
        "api.QueueBuildStepInput": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.RerunBuildFromStepRequest": {
            "type": "object",
            "properties": {
                "step_index": {
                    "type": "integer"
                }
            }
        },
        "api.RetryJobEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.RetryJobResponse"
                }
            }
        },
        "api.RetryJobResponse": {
            "type": "object",
            "properties": {
                "build": {
                    "$ref": "#/definitions/api.BuildResponse"
                },
                "job": {
                    "$ref": "#/definitions/api.ExecutionJobResponse"
                }
            }
        },
        "api.StepLogChunkResponse": {
            "type": "object",
            "properties": {
                "build_id": {
                    "type": "string"
                },
                "chunk_text": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "sequence_no": {
                    "type": "integer"
                },
                "step_id": {
                    "type": "string"
                },
                "step_index": {
                    "type": "integer"
                },
                "step_name": {
                    "type": "string"
                },
                "stream": {
                    "type": "string"
                }
            }
        },
        "api.StepLogsEnvelope": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/api.StepLogsResponse"
                }
            }
        },
        "api.StepLogsResponse": {
            "type": "object",
            "properties": {
                "after": {
                    "type": "integer"
                },
                "build_id": {
                    "type": "string"
                },
                "chunks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.StepLogChunkResponse"
                    }
                },
                "next_sequence": {
                    "type": "integer"
                },
                "step_index": {
                    "type": "integer"
                }
            }
        },
        "api.UpdateJobRequest": {
            "type": "object",
            "properties": {
                "branch_allowlist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "default_commit_sha": {
                    "type": "string"
                },
                "default_ref": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "pipeline_path": {
                    "type": "string"
                },
                "pipeline_yaml": {
                    "type": "string"
                },
                "push_branch": {
                    "type": "string"
                },
                "push_enabled": {
                    "type": "boolean"
                },
                "repository_url": {
                    "type": "string"
                },
                "tag_allowlist": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "trigger_mode": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Coyote CI API",
	Description:      "HTTP API for Coyote CI control-plane workflows.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
