apiVersion: v1
kind: Service
metadata:
  name: coyote-server
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: coyote-server
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: coyote-server
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: coyote-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: coyote-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
